### ISSUE TITLE
EventSub V1

### ISSUE THREAD

**Issue by gempir** [gempir/bitraft#12]
- [x] Privacy policy
- [x] Handle API errors
- [x] Handle retries? 
- [x] Check versions of EventSub
- [ ] ~~cleanup old rewards that are unknown to us, but created by us~~
- [x] Refill DB with twitch response so we can get colors etc
- [x] Handle case where editor removes the last added emote manually -> go random again?
- [x] Update the Redeem Status https://dev.twitch.tv/docs/api/reference#update-redemption-status
- [x] Option to delete rewards/clean old rewards
- [x] Create the custom reward ourselves https://dev.twitch.tv/docs/api/reference#create-custom-rewards
- [x] Login feedback in frontend
- [x] redirect to dashboard after login
- [x] Bot output of messages
- [x] Subscription Deletion?
- [x] More Conditions! Otherwise we do it for every redemption
- [x] output the last removed emote
- [x] handle doubled codes
- [x] revoke invalid accessToken from frontend
- [x] Switch to authorization code flow? https://dev.twitch.tv/docs/authentication/getting-tokens-oauth#oauth-authorization-code-flow
- [x] Refresh tokens
- [x] Somehow private emote got added? https://betterttv.com/emotes/60172c8b8a320865dcf41961
- [x] May 14 12:24:50 sc1 api time="2021-05-14T12:24:50+02:00" level=info msg="Added: 559ad81fa287f9ec6c0a6ff3 60438cc4306b602acc597f80 400"
- [x] Can't be editor for 2 channels?
- [x] Run check for subscriptions on start and remove unused ones

**Comment by gempir** [comment]
Suggested oauth flow:

- click on link, redirect uri api.com/api/callback?code=123
- use code to get accessToken, save it and refreshToken to DB
- api redirects to web.com/dashboard with cookie accessToken

**Comment by gempir** [comment]
![image](https://user-images.githubusercontent.com/9765622/117210064-7ec06f00-adf7-11eb-8e65-788e1b4ecb0a.png)

Somehow still nullable. Should ALWAYS be array

**Comment by gempir** [comment]
```
goroutine 1163 [chan receive]:
github.com/paulbellamy/ratecounter.(*RateCounter).run.func1(0xc000414d40)
        /home/gempir/go/pkg/mod/github.com/paulbellamy/ratecounter@v0.2.0/ratecounter.go:51 +0x8d
created by github.com/paulbellamy/ratecounter.(*RateCounter).run
        /home/gempir/go/pkg/mod/github.com/paulbellamy/ratecounter@v0.2.0/ratecounter.go:48 +0x52

**Comment by gempir** [comment]
- [x] 




```
May 17 17:26:13 sc1 api #011/opt/hostedtoolcache/go/1.15.12/x64/src/net/http/server.go:2969 +0x36c
May 17 17:26:13 sc1 caddy  {"level":"error","ts":1621265173.1348917,"logger":"http.log.error","msg":"EOF","request":{"remote_addr":"35.155.5.226:57632","proto":"HTTP/1.1","method":"POST","host":"spamchamp-api.gempir.com","uri":"/api/redemption","headers":{"Twitch-Eventsub-Subscription-Version":["1"],"Content-Type":["application/json"],"Twitch-Eventsub-Message-Signature":["sha256=43b7e03b355640d2db50d6d68a0463fee669f0628c3729e791747c78fd0294a0"],"Twitch-Eventsub-Message-Timestamp":["2021-05-17T15:25:00.812512256Z"],"Twitch-Eventsub-Subscription-Is-Batching-Enabled":["false"],"Accept-Encoding":["gzip"],"User-Agent":["Go-http-client/1.1"],"Connection":["close"],"Content-Length":["1006"],"Twitch-Eventsub-Message-Id":["dm_qUt3xRitiEIL6UYIpS20hsboVPjWyvgXwDhPzA7A="],"Twitch-Eventsub-Message-Retry":["3"],"Twitch-Eventsub-Message-Type":["notification"],"Twitch-Eventsub-Subscription-Type":["channel.channel_points_custom_reward_redemption.add"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"","proto_mutual":true,"server_name":"spamchamp-api.gempir.com"}},"duration":0.010357321,"status":502,"err_id":"4b3dbs2rb","err_trace":"reverseproxy.statusError (reverseproxy.go:783)"}
May 17 17:26:21 sc1 api time="2021-05-17T17:26:21+02:00" level=info msg="finished refresh of 12 tokens"
May 17 17:34:30 sc1 api 2021/05/17 17:34:30 http: panic serving 127.0.0.1:37490: runtime error: invalid memory address or nil pointer dereference
May 17 17:34:30 sc1 api goroutine 12364753 [running]:
May 17 17:34:30 sc1 api net/http.(*conn).serve.func1(0xc002087cc0)
May 17 17:34:30 sc1 api #011/opt/hostedtoolcache/go/1.15.12/x64/src/net/http/server.go:1801 +0x147
May 17 17:34:30 sc1 api panic(0x7ceea0, 0xae1f10)
May 17 17:34:30 sc1 api #011/opt/hostedtoolcache/go/1.15.12/x64/src/runtime/panic.go:975 +0x47a
May 17 17:34:30 sc1 api github.com/gempir/spamchamp/services/api/server.(*Server).handleChannelPointsRedemption(0xc00036ef60, 0x8b8140, 0xc000e5d180, 0xc0007b0300)
May 17 17:34:30 sc1 api #011/home/runner/work/spamchamp/spamchamp/services/api/server/channelpoints.go:165 +0x599
May 17 17:34:30 sc1 api net/http.HandlerFunc.ServeHTTP(0xc000229540, 0x8b8140, 0xc000e5d180, 0xc0007b0300)
May 17 17:34:30 sc1 api #011/opt/hostedtoolcache/go/1.15.12/x64/src/net/http/server.go:2042 +0x44
May 17 17:34:30 sc1 api net/http.(*ServeMux).ServeHTTP(0xc0003f4700, 0x8b8140, 0xc000e5d180, 0xc0007b0300)
May 17 17:34:30 sc1 api #011/opt/hostedtoolcache/go/1.15.12/x64/src/net/http/server.go:2417 +0x1ad
May 17 17:34:30 sc1 api github.com/rs/cors.(*Cors).Handler.func1(0x8b8140, 0xc000e5d180, 0xc0007b0300)
May 17 17:34:30 sc1 api #011/home/runner/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1b9
May 17 17:34:30 sc1 api net/http.HandlerFunc.ServeHTTP(0xc00036cb60, 0x8b8140, 0xc000e5d180, 0xc0007b0300)
May 17 17:34:30 sc1 api #011/opt/hostedtoolcache/go/1.15.12/x64/src/net/http/server.go:2042 +0x44
May 17 17:34:30 sc1 api net/http.serverHandler.ServeHTTP(0xc0001f40e0, 0x8b8140, 0xc000e5d180, 0xc0007b0300)
May 17 17:34:30 sc1 api #011/opt/hostedtoolcache/go/1.15.12/x64/src/net/http/server.go:2843 +0xa3
May 17 17:34:30 sc1 api net/http.(*conn).serve(0xc002087cc0, 0x8b89c0, 0xc0034c83c0)
May 17 17:34:30 sc1 api #011/opt/hostedtoolcache/go/1.15.12/x64/src/net/http/server.go:1925 +0x8ad
May 17 17:34:30 sc1 api created by net/http.(*Server).Serve
May 17 17:34:30 sc1 api #011/opt/hostedtoolcache/go/1.15.12/x64/src/net/http/server.go:2969 +0x36c
May 17 17:34:30 sc1 caddy  {"level":"error","ts":1621265670.042185,"logger":"http.log.error","msg":"EOF","request":{"remote_addr":"52.12.79.235:8737","proto":"HTTP/1.1","method":"POST","host":"spamchamp-api.gempir.com","uri":"/api/redemption","headers":{"Content-Length":["839"],"Twitch-Eventsub-Subscription-Is-Batching-Enabled":["false"],"Twitch-Eventsub-Subscription-Type":["channel.channel_points_custom_reward_redemption.add"],"Accept-Encoding":["gzip"],"User-Agent":["Go-http-client/1.1"],"Content-Type":["application/json"],"Twitch-Eventsub-Message-Timestamp":["2021-05-17T15:34:29.459962302Z"],"Twitch-Eventsub-Message-Signature":["sha256=9ce5dca1d90f0fc6133d8bee29320280bbdae56fd90a9fbc8006b15558cac3be"],"Twitch-Eventsub-Subscription-Version":["1"],"Twitch-Eventsub-Message-Type":["notification"],"Connection":["close"],"Twitch-Eventsub-Message-Id":["4dSlr1KOKVKdLLLfylf1z-_ds3eemu-R3jskXTucLQg="],"Twitch-Eventsub-Message-Retry":["0"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"","proto_mutual":true,"server_name":"spamchamp-api.gempir.com"}},"duration":0.025902669,"status":502,"err_id":"b76y0h3zd","err_trace":"reverseproxy.statusError (reverseproxy.go:783)"}
May 17 17:34:40 sc1 api 2021/05/17 17:34:40 http: panic serving 127.0.0.1:37492: runtime error: invalid memory address or nil pointer dereference
May 17 17:34:40 sc1 api goroutine 12367241 [running]:
May 17 17:34:40 sc1 api net/http.(*conn).serve.func1(0xc00104f400)
May 17 17:34:40 sc1 api #011/opt/hostedtoolcache/go/1.15.12/x64/src/net/http/server.go:1801 +0x147
```
